export const surpriseMePrompts = [
    "A futuristic cityscape with flying cars and neon lights",
  "A mystical forest with talking animals and glowing plants",
  "An underwater world with mermaids and colorful coral reefs",
  "A steampunk world with gears, cogs, and airships",
  "A surreal landscape with floating islands and upside-down mountains",
  "A post-apocalyptic scene with ruins and overgrown vegetation",
  "A whimsical tea party with animals wearing fancy hats",
  "A space colony on a distant planet with advanced technology",
  "A haunted mansion with flickering candles and ghostly figures",
  "A time-traveling adventure with characters from different eras",
  "An enchanted library with books that come to life",
  "A masquerade ball with elegant costumes and mysterious masks",
  "A journey through a candy-filled wonderland with giant lollipops",
  "A hidden cave with glowing crystals and ancient drawings",
  "A floating island in the sky with waterfalls and lush gardens",
  "A bustling market in a fantasy realm selling magical items",
  "A race of friendly aliens exploring a colorful alien landscape",
  "A world where animals are the rulers and humans are their pets",
  "A frozen kingdom with ice palaces and shimmering snowflakes",
  "A dream-like scene where reality and imagination blend together",
  "A lost city hidden deep within a dense jungle",
  "An alien marketplace with bizarre fruits and peculiar gadgets",
  "A group of wizard apprentices casting spells in a magical academy",
  "A colossal tree that serves as a home for various fantasy creatures",
  "A high-tech cyberpunk street illuminated by holographic advertisements",
  "A desert oasis with a caravan of traders and nomads resting",
  "A dragon tamer riding a majestic fire-breathing dragon in the sky",
  "A massive waterfall flowing upwards into the sky",
  "A peaceful village of tiny cottages nestled among giant mushrooms",
  "A clash between ancient gods in the midst of shaping the world",
  "A hidden underwater cave with bioluminescent aquatic life",
  "A factory producing clouds of different shapes and colors",
  "A superhero team composed of animals with unique powers",
  "A journey through a living dream with shifting landscapes",
  "A concert where musicians are mythical creatures playing fantastical instruments",
  "A grand library filled with floating books and endless knowledge",
  "A secret garden with plants that grow into intricate sculptures",
  "A puppeteer controlling constellations in the night sky",
  "A friendly group of aliens sharing advanced technology with humans",
  "A ceremony where spirits of nature are summoned through dance and music"
];

